#!/usr/bin/env python
#coding:utf-8
# created on 6/30/11

import os
import shutil
import sys

def main():
    """
    Copy the ini file to common location
    """
    this_sys = sys.stdout
    config_path = '/var/files/'
    try:
        shutil.copyfile('./filemover.ini', config_path)
        this_sys.write('filemover.ini copied')
    except IOError, e:
        this_sys.write('Cannot copy file filemover.ini to /var/files/. Please copy the file manually')

